version: "3.8"
services:
  postgres-db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lokillo123
      POSTGRES_DB: TopEducation
    ports:
      - 5432:5432
  app:
    container_name: webapp_topeducation
    image: zthfelipe/webapp_topeducation
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/TopEducation?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=lokillo123
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db
